server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: ProductService-route
          uri: lb://ProductService
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
